// Code generated by MockGen. DO NOT EDIT.
// Source: serviceInterface.go
//
// Generated by this command:
//
//	mockgen -source=serviceInterface.go -destination=../../mocks/service/mock.go -package=service_mock
//

// Package service_mock is a generated GoMock package.
package service_mock

import (
	context "context"
	reflect "reflect"
	domain "shortner/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockLinkService is a mock of LinkService interface.
type MockLinkService struct {
	ctrl     *gomock.Controller
	recorder *MockLinkServiceMockRecorder
	isgomock struct{}
}

// MockLinkServiceMockRecorder is the mock recorder for MockLinkService.
type MockLinkServiceMockRecorder struct {
	mock *MockLinkService
}

// NewMockLinkService creates a new mock instance.
func NewMockLinkService(ctrl *gomock.Controller) *MockLinkService {
	mock := &MockLinkService{ctrl: ctrl}
	mock.recorder = &MockLinkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkService) EXPECT() *MockLinkServiceMockRecorder {
	return m.recorder
}

// GetOriginalLink mocks base method.
func (m *MockLinkService) GetOriginalLink(ctx context.Context, alias string) (*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalLink", ctx, alias)
	ret0, _ := ret[0].(*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalLink indicates an expected call of GetOriginalLink.
func (mr *MockLinkServiceMockRecorder) GetOriginalLink(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalLink", reflect.TypeOf((*MockLinkService)(nil).GetOriginalLink), ctx, alias)
}

// ShortenLink mocks base method.
func (m *MockLinkService) ShortenLink(ctx context.Context, link string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortenLink", ctx, link)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortenLink indicates an expected call of ShortenLink.
func (mr *MockLinkServiceMockRecorder) ShortenLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortenLink", reflect.TypeOf((*MockLinkService)(nil).ShortenLink), ctx, link)
}
